create johnbeatrice.md
open-learning-exchange/open-learning-exchange.github.io pull request #3146
Opened 2022-02-18 19:54 UTC by johnbeatrice

Raw.githack link to document:

https://raw.githack.com/johnbeatrice/johnbeatriceOLE.github.io/johnbeatrice-first-branch/#!pages/vi/profiles/johnbeatrice.md

2022-02-19 19:58 UTC, dcwebdev commented
Hi, I'd like to unsubscribe from this thread, but the unsubscribe link
doesn't work for me. Could a project manager remove my email from the list,
please?

On Fri, Feb 18, 2022 at 2:54 PM johnbeatrice ***@***.***>
wrote:

> Raw.githack link to document:
>
>
> https://raw.githack.com/johnbeatrice/johnbeatriceOLE.github.io/johnbeatrice-first-branch/#!pages/vi/profiles/johnbeatrice.md
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>
> https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146
> Commit Summary
>
>    - 6caa619
>    <https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146/commits/6caa619364ec20eff1f4ccc064528360105a4bf0>
>    Create johnbeatrice.md
>    - ef5970d
>    <https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146/commits/ef5970d09e7da205c3cc0bb2ae85425fe0395e49>
>    Update johnbeatrice.md
>
> File Changes
>
> (1 file
> <https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146/files>
> )
>
>    - *A* pages/vi/profiles/johnbeatrice.md
>    <https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146/files#diff-775b998dda35177aeb951d8662c70ed093aad597fcaaef54ef32fdddec411c92>
>    (15)
>
> Patch Links:
>
>    -
>    https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146.patch
>    -
>    https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/3146>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF4EGGWNQYHT76QRCOZSV3DU32PXVANCNFSM5OY5OCQA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you are subscribed to this thread.Message
> ID: <open-learning-exchange/open-learning-exchange.github.io/pull/3146@
> github.com>
>

2022-02-21 09:05 UTC, lmmrssa requested changes

2022-02-21 09:05 UTC, lmmrssa commented on pages/vi/profiles/johnbeatrice.md
> +Hi there, I`m a self-taught web developer transitioning careers, and I'm very excited to be a part of OLE! I've worked in a variety of industries before now but I feel I've found a great fit in tech
"`" in this line will be an issue please use normal quote.

2022-02-22 00:38 UTC, lmmrssa commented on pages/vi/profiles/johnbeatrice.md
> +* __LinkedIn:__ https://www.linkedin.com/in/john-beatrice-2071a8218/
please use markdown for the link. Right now it is browser which is showing it as link not the markdown

2022-02-23 09:46 UTC, lmmrssa commented on pages/robots/rbts-myplanet.md
> -## Usefull Links
This should be separate PR so please clean this PR just to put your profile file and create separate PR for this issue

2022-02-24 02:22 UTC, lmmrssa approved these changes

2022-02-24 02:22 UTC, merged