add axzhir.md
open-learning-exchange/open-learning-exchange.github.io pull request #3215
Opened 2024-05-08 14:45 UTC by axzihr

https://github.com/axzihr/axzhir.github.io/blob/add-axzhir-profile/axzhir.md

2024-05-08 15:29 UTC, xyb994 requested changes
Could you also edit the pull request description and provide the raw.githack preview link to your profile as laid out in the pull  request template / step 1?

2024-05-08 15:29 UTC, xyb994 commented on axzhir.md
> +    2. GitHub -> https://github.com/axzihr
@axzhir It looks like your github username got misspelled.

2024-05-08 15:46 UTC, dogi requested changes
please use some more complex markdown elements
- link
- picture
- table

2024-05-09 05:11 UTC, xyb994 requested changes
The file appear to be located directly in the repository's root folder while we meant to ask you to add it to `pages/mi/profiles/` folder. Could you move it with the proper directory at https://docs.github.com/en/repositories/working-with-files/managing-files/moving-a-file-to-a-new-location ?

2024-05-12 06:08 UTC, dogi approved these changes

2024-05-13 10:25 UTC, Okuro3499 commented
@axzhir I can noww see your profile could you check https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md#Step_8_-_Create_Issues_and_Pull_Requests to update your pr title to include the issue number

2024-05-13 10:26 UTC, Okuro3499 requested changes
@axzhir I can now see your profile could you check https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md#Step_8_-_Create_Issues_and_Pull_Requests to update your pr title to include the issue number

2024-05-13 15:06 UTC, xyb994 approved these changes

2024-05-13 17:37 UTC, merged