update vi-create-issues-and-pull-requests.md
open-learning-exchange/open-learning-exchange.github.io pull request #3531
Opened 2024-12-25 16:36 UTC by Avinash-Codes

**Important:** *Do not tick a checkbox if you haven’t performed its action.*

### Before Creating the Pull Request

- [x] Verify the changes are on a new branch other than `master` – it should say "compare: branch-name".
- [x] Start the pull request title with lowercase letters, e.g., `add githubusername.md`.
- [x] Add issue number to the end of the pull request title when applicable, e.g., `update mi-faq.md (fixes #3264)`.

### After Creating the Pull Request

- [x] Go to "Commits" tab, make sure the commit username is clickable and linked to your GitHub account correctly.
- [x] Review the "Files changed" tab to ensure there are no unnecessary files or changes included in the pull request.
- [x] Verify that the raw.githack preview link is included in the description.
 - [x] Preview the MDwiki rendered changes using the raw.githack link. Ensure it displays as expected without any errors.
- [x] Drop a link to this pull request in our discord channel.

### Description, Screenshots and/or Screencast

fixes #

### Raw.Githack Preview Link

2024-12-30 22:06 UTC, xyb994 commented on pages/vi/vi-create-issues-and-pull-requests.md
> +<img src="https://github.com/user-attachments/assets/ce061b97-9420-49c6-aa8c-e9ce97dd2708" width="800" alt="Planet.vi Homepage">
I wonder where you uploaded the images? One of the potential issue I see is that [those images might be deleted after some time](https://github.com/orgs/community/discussions/77006).

Could you add them to `pages/vi/images/` instead?

2025-01-01 12:44 UTC, Avinash-Codes commented on pages/vi/vi-create-issues-and-pull-requests.md
> +<img src="https://github.com/user-attachments/assets/ce061b97-9420-49c6-aa8c-e9ce97dd2708" width="800" alt="Planet.vi Homepage">
Okay, I wasn’t aware that there’s a time limit for keeping images in GitHub. I’ll upload the images to the assigned folder mentioned above

2025-01-03 16:39 UTC, jessewashburn requested changes
These instructions are very clear. I'm not sure this is the right place for them, as this section is about creating issues and pull requests.

2025-01-04 00:54 UTC, xyb994 commented
> These instructions are very clear. I'm not sure this is the right place for them, as this section is about creating issues and pull requests.

This did come across my mind. Perhaps we could move this addition to a separate page under `vi` so we can link to it as one of the required issue/pr similar to asking vi working on the manual?

2025-01-17 16:51 UTC, merged